# Generated by Django 5.2.8 on 2026-03-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome do livro', max_length=100, verbose_name='Livro')),
                ('autor', models.CharField(help_text='Nome do autor', max_length=100, verbose_name='Autor')),
                ('categoria', models.CharField(help_text='Romance, Terror etc..', max_length=50, verbose_name='Categoria')),
                ('disponivel', models.BooleanField(default=True, help_text='O livro está disponível?', verbose_name='Disponível?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do usuário', max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Email do usuário', max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(help_text='Data do empréstimo', verbose_name='Data do empréstimo')),
                ('data_prevista_devolucao', models.DateField(help_text='Quando o livro será devolvido', verbose_name='Data prevista para devolução')),
                ('data_devolucao', models.DateField(blank=True, help_text='Data que o livro foi devolvido', null=True, verbose_name='Data de devolução')),
                ('ativo', models.BooleanField(default=True, help_text='O empréstimo está ativo?', verbose_name='O empréstimo ativo?')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
