# Generated by Django 5.2.8 on 2026-06-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor da multa', max_digits=6, verbose_name='Valor da multa'),
        ),
    ]
