# Generated by Django 5.2.8 on 2026-06-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_emprestimo_valor_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade_renovacoes',
            field=models.PositiveIntegerField(default=0, help_text='Quantas vezes a obra já foi renovada', verbose_name='Quantidade de renovações'),
        ),
    ]
