# Generated by Django 5.2.8 on 2026-06-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0003_emprestimo_quantidade_renovacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, help_text='Quando o livro será devolvido', null=True, verbose_name='Data prevista para devolução'),
        ),
    ]
